# -*- coding: utf-8 -*-
"""
Created on 2024-12-25 12:52:51
---------
@summary:
---------
@author: Admin
"""

from feapder import Item


class DetialListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i detial_list
    """

    __table_name__ = "detial_list"

    def __init__(self, *args, **kwargs):
        self.title = None
        self.name = None
        # self.courseId = None
        self.kngId = None
        self.studyHours = None
        self.studyScore = None
        # self.studyStatus = 0
