# -*- coding: utf-8 -*-
"""
Created on 2024-12-25 13:02:48
---------
@summary:
---------
@author: Admin
"""

from feapder import Item


class TotalListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i total_list
    """

    __table_name__ = "total_list"

    def __init__(self, *args, **kwargs):
        self.title = None
        self.Id = None
        self.studyScore = None
        # self.status = 0
        self.studyHours = None
